modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="https://github.com/bh679/adventureitemstats-mc/issues"

[[mods]]
modId="adventureitemstats"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayURL="https://github.com/bh679/adventureitemstats-mc"
logoFile="logo.png"

[[mixins]]
config="adventureitemstats.mixins.json"

[[dependencies.adventureitemstats]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.adventureitemstats]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
